/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActivityInfo: typeof import('./components/ActivityInfo.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    DecomposeTextField: typeof import('./components/reader/DecomposeTextField.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    OperatorInfo: typeof import('./components/OperatorInfo.vue')['default']
    PoolInfo: typeof import('./components/PoolInfo.vue')['default']
    Reader: typeof import('./components/reader/Reader.vue')['default']
    ReaderSwitch: typeof import('./components/reader/ReaderSwitch.vue')['default']
    ReaderText: typeof import('./components/reader/ReaderText.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SwitchList: typeof import('./components/reader/SwitchList.vue')['default']
    TimelineInventory: typeof import('./components/TimelineInventory.vue')['default']
    TimelineItem: typeof import('./components/TimelineItem.vue')['default']
  }
}
